Feature/add-MainTabView-FeedView-CustomColor
wafflestudio/22-5-team5-iOS pull request #3
Opened 2024-12-25 07:11 UTC by joongwon0204

###PR 타입(하나 이상의 PR 타입을 선택해주세요)
-[O] 기능 추가 
-[] 기능 삭제
 -[] 버그 수정
 -[] 의존성, 환경 변수, 빌드 관련 코드 업데이트

###반영 브랜치
 feat/add-feed-view -> main

###변경 사항
MainTabView 생성
 FeedView, FeedCell 생성 및 연결
CustomColor 생성

###추후 보완 사항 
Data 받아오기 및 연결
CustomColor 정하기

2024-12-25 18:55 UTC, muzigae requested changes

2024-12-25 18:55 UTC, muzigae commented on Wastory/Wastory/CustomColor.swift
어떤 부분인지 느낌은 오는데 전체적으로 쓰일 색이니 주석으로 용도를 표기해 주시면 좋을 것 같아요.

2024-12-25 18:55 UTC, muzigae commented on Wastory/Wastory/WastoryApp.swift
티스토리 앱을 처음에 켜면 빨간색에 중앙에 T가 그려진 로딩 화면이 나오는 것을 확인했습니다. 제가 그것을 만들 예정인데, 맨 처음에 WindowGroup에서 LoadingView를 넣고 UserDefault로 ID, PW를 불러와서 존재한다면 자동 로그인 후 MainTabView로, 존재하지 않는다면 로그인 화면으로 넘어가고, 로그인에 성공하면 MainTabView, 실패한다면 회원가입 화면을 띄운 후 넘어가는 구조로 생각하고 있습니다.

2024-12-25 18:55 UTC, muzigae commented on Wastory/Wastory/View/MainTabView.swift
전반적인 구조를 깔끔하게 잘 만들어 주셔서 수정할 곳은 없어 보입니다. 나중에 탭 아이콘의 세부적인 디테일을 어떻게 할지 상의해야 할 것 같아요.

2024-12-25 18:55 UTC, muzigae commented on Wastory/Wastory/View/FeedView/FeedView.swift
![241226_빌드이슈2](https://github.com/user-attachments/assets/da5a65e7-e329-42b2-8ca3-2c93aec206e6)
![241226_빌드이슈1](https://github.com/user-attachments/assets/c64134de-004c-441f-a94d-dd57ad934d1a)
제가 코드를 직접 실행해 보려고 했으나 빌드가 되지 않는 것을 확인하였습니다. 윗 화면이 중원님 파일을 클론하여 실행한 것이고, 아래 화면은 제 기존 과제의 xcode 실행 화면입니다. 저희가 놓친 부분이 하나 있는데 저희가 사용하는 xcode 버전이 다를 확률이 높을 것 같습니다. 실제로 제가 세미나 참여할 때도 세미나장님이 이런 이슈로 채점에 어려움을 겪은 적이 있으셨습니다. 우선 이것을 통일해야 할 것 같아요.
추가적으로 저희가 세미나 마지막에 MVVM 모델과 클린 코드에 대해 배웠었는데 subscribingCount, subscriberCount 등은 추후 viewModel로 관리하실 계획이신가요? 이런 구조도 상의하여 통일하는 것이 좋아 보입니다.
FeedView와 FeedViewCell은 버전 통일 이후 빌드하여 확인한 다음에 다시 review 해야 할 것 같아요.

2024-12-26 00:44 UTC, joongwon0204 commented on Wastory/Wastory/View/FeedView/FeedView.swift
<img width="1280" alt="스크린샷 2024-12-26 09 40 42" src="https://github.com/user-attachments/assets/7d0cfcca-ac84-4e18-aa95-41f0084705b5" />
<img width="539" alt="스크린샷 2024-12-26 09 41 28" src="https://github.com/user-attachments/assets/ec4b40ec-fcd5-4eb6-8ab9-5bc133748574" />
<img width="539" alt="스크린샷 2024-12-26 09 43 50" src="https://github.com/user-attachments/assets/6ba8cc44-8692-4879-b8a6-82532e7a624c" />

데이터연결하는 부분은 viewModel로 관리하는게 좋아보여요

일단 Xcode 버전 보내드렸습니다. 혹시 어떤 버전이 문제인지 확인 부탁드려요

2024-12-26 00:48 UTC, joongwon0204 commented on Wastory/Wastory/View/MainTabView.swift
탭 아이콘 이미지를 system symbol 중에서 최대한 비슷한 것으로 하는 것, 아니면 캡쳐 등을 통해서 이미지를 직접 넣는 것, 어떤 게 나으신가요?

2024-12-26 00:55 UTC, joongwon0204 commented on Wastory/Wastory/CustomColor.swift
일단 파일 생성을 위해서 임의로 하나 넣어놨습니다. primaryLabelColor, secondaryLabelColor 등 상의해서 넣을면 될 것 같아요.

2024-12-26 03:46 UTC, muzigae commented on Wastory/Wastory/View/MainTabView.swift
system symbol이 사실 편하겠지만 운영진에게 질문해보고 판단해야 할 것 같아요. 디자인도 카피하는 게 클론 프로젝트의 목표였어서 나중에 한 번 여쭤봐야겠네요.

2024-12-26 03:50 UTC, muzigae commented on Wastory/Wastory/View/FeedView/FeedView.swift
티스토리 피드와 비교해 보았는데 상당히 잘 만들어 주신 것 같습니다. 한 가지 달랐던 점이 "5분 전"이라고 표기된 부분이었는데 혹시 iOS에서는 ~전으로 표기가 되는 걸까요? 제가 볼 때는 ~전이 아닌 글 작성 날짜 "2024. 12. 9."와 같은 방식으로 나타나긴 합니다. 이 부분은 확인만 해주시고 나중에 글 정보를 불러올 수 있게 되었을 때 다시 검토하면서 수정하면 좋을 것 같습니다. 제 생각에는 이제 merge해도 문제 없을 것 같습니다!

2024-12-26 03:51 UTC, muzigae approved these changes

2024-12-26 04:23 UTC, merged